language: C++
sudo: false
git:
    depth: 1
addons:
  apt:
    sources:
       - ubuntu-toolchain-r-test
    packages:
       - g++-5
os:
  - linux
cache:
  ccache: true
  directories:
    - node_modules
install:
  - npm install
  - pip install --user cpp-coveralls
before_script:
  - export CXX="g++-5"
  - export CC="gcc-5"
  - export GCOV="gcov-5"
script:
  - mkdir build && cd build
  - cmake -DB9_GCOV=ON ..
  - make -j4 || echo "*BUILD_FAILURE*" && make -j1 VERBOSE=1
  - ctest --output-on-failure
  - cd "${TRAVIS_BUILD_DIR}"
after_script:
  - echo "Uploading code coverage report"
  - coveralls --exclude third_party --gcov $(which $GCOV) --gcov-options '\-lp' --build-root build > /dev/null
