# Site Settings
title: Base9
description: >
  An educational virtual machine built with Eclipse OMR
# baseurl: /b9
github_username: b9org
theme: minima
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
markdown: kramdown
highlighter: rouge
collections:
  - build-a-runtime
  - docs
  - setup
defaults:
  - scope:
      path: docs
    values:
      section: docs
  - scope:
      path: setup
    values:
      section: setup
  - scope:
      path: build-a-runtime
    values:
      section: build-a-runtime
